### PR TITLE
Fix time offset on Wii

### PR DESCRIPTION
**Pull request by endrift**
I guess this function was necessary after all.

### CODE REVIEW

**Comment by bladeoner** [comment]
@endrift is your fix only to fix the offset of the time or also the time itself?

With snes9x gx I got the issue that the clock is not working, I tried to compile the libogc with your fix and replaced libogc.a in the libogc folder / Wii folder but when I compile the source of snes9x gx and try to start it I get a black screen. Any idea if I do something wrong?

Thanks in advance.

**Comment by Fledge68** [comment]
i'm having issues with time(null) on wii.  it seems to always start at jan 1 2000 0:00:00
i tried this fix and compiled wiiflow lite but now it hangs on startup and it seems to be when the first time(null) in the code occurs.

**Comment by endrift** [comment]
I'll try to investigate later today.

**Comment by WinterMute** [comment]
This doesn't seem to work on hardware and hangs on exit to HBC.

Still need to dig out a cube & test there

**Comment by endrift** [comment]
This version should work now. Needs to be tested on GC though.

**Comment by WinterMute** [comment]
I replaced the SYS_Time call with gettime locally and, while it works in Dolphin, the time is quite wrong on hardware via HBC. Was coming back as November 25, 2010 rather than November 11, 2018.

**Comment by endrift** [comment]
Fixed now. Turns out SYS_Time was calling into a CONF_* function before CONF_Init was called.

**Comment by bladeoner** [comment]
Thank you for the time fix.

**Pull request merged**
