### PR TITLE
introduce sram flags to libogc

### PR DESCRIPTION
**Pull request by DacoTaco**
just introducing the sram flags to libogc.

### CODE REVIEW

**Comment by Extrems** [comment]
I'll just leave this here.
https://github.com/extremscorner/libogc-rice/commit/d96cb10c0544e02212529ee3c2f7dcfa9a9a2a37

**Comment by WinterMute** [comment]
> I'll just leave this here.

You could always make a PR and try to work with other people instead of whatever it is you're doing.

**Comment by Extrems** [comment]
It's there for someone to pick it up.

**Comment by endrift** [comment]
Sorry, people don't generally trawl your backlog of commits that you haven't exactly publicized exist in the first place. The onus isn't on devkitPro to look through every fork to find relevant commits.

**Pull request closed without merging**
