### PR TITLE
Improve video quality on Wii

### PR DESCRIPTION
**Pull request by Extrems**

### CODE REVIEW

**Comment by endrift** [comment]
Got around to testing this (albeit on component cables). Looks good to me.

**Comment by gingerbeardman** [comment]
This looks good to me also

**Comment by gingerbeardman** [comment]
Here are some photos of my 640x480p LCD displaying Mario Kart Wii both with and without the 480p fix. 

It's best if you download full size photos and compare them in an image viewer rather than your web browser. 

**Places to look for differences**
1. e of Channel
2. inside the a of Back
3. glasses frame on my Mii
4. Ms of Main Menu

**Conclusion**
- fixed: graphics are pixel aligned horizontally
- original: graphics are not pixel aligned horizontally

https://imgur.com/a/R0k3igo

**Comment by WinterMute** [comment]
This should at least have some explanation of what the mode parameter actually does. It would be good if there were named parameters rather than just random numbers.

**Pull request merged**
