### PR TITLE
SD/SI related fixes

### PR DESCRIPTION
**Pull request by emukidid**
The setSpeed and pageSize functions are extensively only used in Swiss as far as I'm aware so this shouldn't break anything else.

### CODE REVIEW

**Comment by WinterMute** [comment]
@emukidid Could you possibly redo this PR with the relevant changes in a topic branch rather than have unrelated commits continually added before anyone gets a chance to actually look at the changes properly.

**Comment by emukidid** [comment]
At best I can rename it to "Fix miscellaneous issues" since that's what my fork has been set out to do for the most part from day one. We run into bugs/limitations when trying to use various parts of libOGC that aren't commonly used and instead of having to wait, we just patch my fork so that we can move on.

The commits themselves have enough meaning through their commit messages. If you want me to create separate branches I'd be happy to but it will end up being more work for you. I'd rather just periodically make a pull request to merge master in.

**Comment by WinterMute** [comment]
@emukidid It's more work for me if there are multiple features changed/fixed within a single PR.  It would be better if you used a topic/feature branch & PR'd that. It would also be helpful if macro and/or variable names weren't changed without a good reason (for example, there's no reason to change _ERR to ERROR - it doesn't add any useful information and breaks old code with no benefit)

It's kind of difficult to work through a PR with multiple unrelated changes as it is without the PR changing underneath you.

**Comment by WinterMute** [comment]
These changes need PR'd separately. Please don't continue adding to it.

**Pull request closed without merging**
